services:
  anvil:
    image: "ghcr.io/foundry-rs/foundry:latest"
    command: "'anvil --host 0.0.0.0 --port=11111'"
    ports:
      - "11111:11111"
    depends_on:
      - compiler
    labels:
      net.consensys.description: >
        Starts an instance of anvil on port 11111 for chain parity tests.

  compiler:
    image: "ethereum/solc:stable"
    command: "--abi --bin -o /tmp/contracts/build --overwrite /tmp/contracts/hash_test_contract.sol"
    volumes:
      - ./tests/contracts:/tmp/contracts
    labels:
      net.consensys.description: >
        Compiles ./tests/contracts/hash_test_contract.sol. Places generated files in ./tests/contracts/build/.
        Generates JSON ABI and Bytecode hex: TestContract.abi, TestContract.bin.
        See ./tests/test_chain_parity.py::contract to see how this is deployed.
