name: lint

on:
  push:
    branches:
      - main
      - update
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{github.token}}

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          token: ${{github.token}}

      - name: install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: install project
        run: |
          uv venv .venv -p 3.12
          source .venv/bin/activate
          uv pip install -e .[all]

      - name: lint with ruff
        run: |
          source .venv/bin/activate
          python -m ruff check .
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{github.token}}

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
          token: ${{github.token}}

      - name: install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: install project
        run: |
          uv venv .venv -p ${{matrix.python-version}}
          source .venv/bin/activate
          uv pip install -e .[all]

      - name: test
        run: |
          source .venv/bin/activate
          python -m pytest .
